

import { Inter } from 'next/font/google'
import NavScrollExample from './components/navbar'
import 'bootstrap/dist/css/bootstrap.min.css';
import Footer from './components/Footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'repo1',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body >
      <NavScrollExample/>
       
        {children}
      
        <Footer/>
        </body>
    </html>
  )
}
